# Compose file for the Motorcycle Club project
# - TypeScript/Next.js frontend (node-app)
# - C# .NET API backend (dotnet-api)
#
# No explicit external services (databases, caches, etc.) detected in README or codebase.
#
services:
  ts-app:
    # TypeScript/Next.js frontend
    container_name: ts-app
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    init: true
    ports:
      - "3000:3000"  # Next.js default port
    # env_file: ./.env  # Uncomment if .env file exists
    networks:
      - mcnet
    depends_on:
      - dotnet-api

  dotnet-api:
    # C# .NET API backend
    container_name: dotnet-api
    build:
      context: ./src/api
      dockerfile: ./src/api/Dockerfile
    restart: unless-stopped
    ports:
      - "8080:80"    # Map host 8080 to container 80 (HTTP)
      # - "8443:443" # Uncomment if HTTPS is configured
    # env_file: ./src/api/.env  # Uncomment if .env file exists
    networks:
      - mcnet

networks:
  mcnet:
    driver: bridge
